import pygrib
import numpy as np
import netCDF4 as nc


def changeto_nc():
    newfile = nc.Dataset('./nc_data/2022-12-12/gfs.t00z.pgrb2.0p25_1hr.f001.nc', 'w', format='NETCDF4')
    file_name = './gfs_data/2022-12-12/gfs.t00z.pgrb2.0p25_1hr.f001'

    ds = pygrib.open(file_name)

    long = newfile.createDimension('longitude', size=1440)
    lati = newfile.createDimension('latitude', size=721)

    lon = newfile.createVariable('lon', 'f4', dimensions='longitude')
    lat = newfile.createVariable('lat', 'f4', dimensions='latitude')

    temps = newfile.createVariable('temperature', 'f4', dimensions=('longitude', 'latitude'))
    press = newfile.createVariable('pressure', 'f4', dimensions=('longitude', 'latitude'))
    gusts = newfile.createVariable('wind', 'f4', dimensions=('longitude', 'latitude'))
    # apcps = newfile.createVariable('precipitation', 'f4', dimensions=('longitude', 'latitude'))

    temp = np.rot90(np.rot90(np.rot90(ds.select(name='Temperature')[0].values)))
    pres = np.rot90(np.rot90(np.rot90(ds.select(name='Pressure')[0].values)))
    gust = np.rot90(np.rot90(np.rot90(ds.select(name='Wind speed (gust)')[0].values)))
    # apcp = np.rot90(np.rot90(np.rot90(ds.select(name='Total Precipitation')[0].values)))

    lon[:] = np.arange(0, 360, 0.25)
    lat[:] = np.arange(-90, 90.25, 0.25)

    temps[...] = temp
    press[...] = pres
    gusts[...] = gust
    # apcps[...] = apcp

    lon.description = 'longitude, west is negative'
    lon.units = 'degrees east'
    lat.description = 'latitude, south is negative'
    lat.units = 'degrees north'
    temps.description = 'temperature, random value generated by numpy'
    temps.units = 'degree'
    temps.coordinates = "lat lon"
    press.description = 'pressure, random value generated by numpy'
    press.units = 'degree'
    press.coordinates = "lat lon"
    gusts.description = 'wind, random value generated by numpy'
    gusts.units = 'degree'
    gusts.coordinates = "lat lon"
    # apcps.description = 'precipitation, random value generated by numpy'
    # apcps.units = 'degree'
    # apcps.coordinates = "lat lon"

    newfile.close()


if __name__ == '__main__':
    changeto_nc()
