import pygrib
import numpy as np
import netCDF4 as nc


def changeto_nc():
    if i == 0:
        newfile = nc.Dataset('../nc_Data/gfs.t00z.pgrb2.0p25.f00{}.nc'.format(i), 'w', format='NETCDF4')
        file_name = '../Data/gfs.t00z.pgrb2.0p25.f00{}'.format(i)

        ds = pygrib.open(file_name)

        long = newfile.createDimension('longitude', size=1440)
        lati = newfile.createDimension('latitude', size=721)

        lon = newfile.createVariable('lon', 'f4', dimensions='longitude')
        lat = newfile.createVariable('lat', 'f4', dimensions='latitude')

        temps = newfile.createVariable('temperature', 'f4', dimensions=('longitude', 'latitude'))
        press = newfile.createVariable('pressure', 'f4', dimensions=('longitude', 'latitude'))
        gusts = newfile.createVariable('wind', 'f4', dimensions=('longitude', 'latitude'))
        apcps = newfile.createVariable('precipitation', 'f4', dimensions=('longitude', 'latitude'))

        temp = np.rot90(np.rot90(np.rot90(ds.select(name='Temperature')[0].values)))
        pres = np.rot90(np.rot90(np.rot90(ds.select(name='Surface pressure')[0].values)))
        gust = np.rot90(np.rot90(np.rot90(ds.select(name='Wind speed (gust)')[0].values)))
        apcp = gust
        for x_dim in range(apcp.shape[0]):
            for y_dim in range(apcp.shape[1]):
                apcp[x_dim][y_dim] = 0

        lon[:] = np.arange(0, 360, 0.25)
        lat[:] = np.arange(-90, 90.25, 0.25)

        temps[...] = temp
        press[...] = pres
        gusts[...] = gust
        apcps[...] = apcp

        lon.description = 'longitude, west is negative'
        lon.units = 'degrees east'
        lat.description = 'latitude, south is negative'
        lat.units = 'degrees north'
        temps.description = 'temperature, random value generated by numpy'
        temps.units = 'degree'
        temps.coordinates = "lat lon"
        press.description = 'pressure, random value generated by numpy'
        press.units = 'degree'
        press.coordinates = "lat lon"
        gusts.description = 'wind, random value generated by numpy'
        gusts.units = 'degree'
        gusts.coordinates = "lat lon"
        apcps.description = 'precipitation, random value generated by numpy'
        apcps.units = 'degree'
        apcps.coordinates = "lat lon"

        newfile.close()
    elif 1 <= i < 10:
        newfile = nc.Dataset('../nc_Data/gfs.t00z.pgrb2.0p25.f00{}.nc'.format(i), 'w', format='NETCDF4')
        file_name = '../Data/gfs.t00z.pgrb2.0p25.f00{}'.format(i)

        ds = pygrib.open(file_name)

        long = newfile.createDimension('longitude', size=1440)
        lati = newfile.createDimension('latitude', size=721)

        lon = newfile.createVariable('lon', 'f4', dimensions='longitude')
        lat = newfile.createVariable('lat', 'f4', dimensions='latitude')

        temps = newfile.createVariable('temperature', 'f4', dimensions=('longitude', 'latitude'))
        press = newfile.createVariable('pressure', 'f4', dimensions=('longitude', 'latitude'))
        gusts = newfile.createVariable('wind', 'f4', dimensions=('longitude', 'latitude'))
        apcps = newfile.createVariable('precipitation', 'f4', dimensions=('longitude', 'latitude'))

        temp = np.rot90(np.rot90(np.rot90(ds.select(name='Temperature')[0].values)))
        pres = np.rot90(np.rot90(np.rot90(ds.select(name='Surface pressure')[0].values)))
        gust = np.rot90(np.rot90(np.rot90(ds.select(name='Wind speed (gust)')[0].values)))
        apcp = np.rot90(np.rot90(np.rot90(ds.select(name='Total Precipitation')[0].values)))

        lon[:] = np.arange(0, 360, 0.25)
        lat[:] = np.arange(-90, 90.25, 0.25)

        temps[...] = temp
        press[...] = pres
        gusts[...] = gust
        apcps[...] = apcp

        lon.description = 'longitude, west is negative'
        lon.units = 'degrees east'
        lat.description = 'latitude, south is negative'
        lat.units = 'degrees north'
        temps.description = 'temperature, random value generated by numpy'
        temps.units = 'degree'
        temps.coordinates = "lat lon"
        press.description = 'pressure, random value generated by numpy'
        press.units = 'degree'
        press.coordinates = "lat lon"
        gusts.description = 'wind, random value generated by numpy'
        gusts.units = 'degree'
        gusts.coordinates = "lat lon"
        apcps.description = 'precipitation, random value generated by numpy'
        apcps.units = 'degree'
        apcps.coordinates = "lat lon"

        newfile.close()
    else:
        newfile = nc.Dataset('../nc_Data/gfs.t00z.pgrb2.0p25.f0{}.nc'.format(i), 'w', format='NETCDF4')
        file_name = '../Data/gfs.t00z.pgrb2.0p25.f0{}'.format(i)

        ds = pygrib.open(file_name)

        long = newfile.createDimension('longitude', size=1440)
        lati = newfile.createDimension('latitude', size=721)

        lon = newfile.createVariable('lon', 'f4', dimensions='longitude')
        lat = newfile.createVariable('lat', 'f4', dimensions='latitude')

        temps = newfile.createVariable('temperature', 'f4', dimensions=('longitude', 'latitude'))
        press = newfile.createVariable('pressure', 'f4', dimensions=('longitude', 'latitude'))
        gusts = newfile.createVariable('wind', 'f4', dimensions=('longitude', 'latitude'))
        apcps = newfile.createVariable('precipitation', 'f4', dimensions=('longitude', 'latitude'))

        temp = np.rot90(np.rot90(np.rot90(ds.select(name='Temperature')[0].values)))
        pres = np.rot90(np.rot90(np.rot90(ds.select(name='Surface pressure')[0].values)))
        gust = np.rot90(np.rot90(np.rot90(ds.select(name='Wind speed (gust)')[0].values)))
        apcp = np.rot90(np.rot90(np.rot90(ds.select(name='Total Precipitation')[0].values)))

        lon[:] = np.arange(0, 360, 0.25)
        lat[:] = np.arange(-90, 90.25, 0.25)

        temps[...] = temp
        press[...] = pres
        gusts[...] = gust
        apcps[...] = apcp

        lon.description = 'longitude, west is negative'
        lon.units = 'degrees east'
        lat.description = 'latitude, south is negative'
        lat.units = 'degrees north'
        temps.description = 'temperature, random value generated by numpy'
        temps.units = 'degree'
        temps.coordinates = "lat lon"
        press.description = 'pressure, random value generated by numpy'
        press.units = 'degree'
        press.coordinates = "lat lon"
        gusts.description = 'wind, random value generated by numpy'
        gusts.units = 'degree'
        gusts.coordinates = "lat lon"
        apcps.description = 'precipitation, random value generated by numpy'
        apcps.units = 'degree'
        apcps.coordinates = "lat lon"

        newfile.close()


if __name__ == '__main__':
    for i in range(1):
        changeto_nc()
